import React from "react";
import {  PictureAsPdf } from "@mui/icons-material";

const Profile = () => {

  const profile = {
    name: "Dr. Evelyn Reed",
    department: "Computer Science & Engineering",
    subject: "Web Development",
    email: "evelyn.reed@university.edu",
    phone: "+1 (123) 456-7890",
    avatar: "https://cdn-icons-png.flaticon.com/512/706/706830.png",
  };


  const materials = [
    { title: "MERN Stack", date: "Oct 26, 2023" },
    { title: "Introduction to React", date: "Oct 24, 2023" },
    { title: "State Management", date: "Oct 22, 2023" },
    { title: "Advanced CSS", date: "Oct 20, 2023" },
  ];

  return (
    <div className="p-8  min-h-screen">
     
      <div className="flex flex-col lg:flex-row gap-8 max-w-6xl mx-auto">
        {/* Left Column - Profile Details */}
        <div className="bg-white rounded-2xl shadow-md p-6 flex-1 relative">
          <div className="flex flex-col items-center">
            <img
              src={profile.avatar}
              alt="Profile"
              className="w-28 h-28 rounded-full border-4 border-green-100 shadow-sm mb-3"
            />
            <h2 className="text-2xl font-bold text-gray-800">{profile.name}</h2>
            <p className="text-gray-500 text-sm">{profile.department}</p>
            <div className="h-0.5 w-24 bg-green-400 mt-2 rounded-full"></div>
          </div>

          <div className="space-y-4 text-sm mt-6">
            <div>
              <p className="text-gray-500">Name</p>
              <p className="font-medium">{profile.name}</p>
            </div>
            <div>
              <p className="text-gray-500">Department</p>
              <p className="font-medium">{profile.department}</p>
            </div>
            <div>
              <p className="text-gray-500">Subject</p>
              <p className="font-medium">{profile.subject}</p>
            </div>
            <div>
              <p className="text-gray-500">Email</p>
              <p className="font-medium">{profile.email}</p>
            </div>
            <div>
              <p className="text-gray-500">Phone</p>
              <p className="font-medium">{profile.phone}</p>
            </div>
          </div>
        </div>

        {/* Right Column - Course Materials */}
        <div
          style={{ maxHeight: "550px" }}
          className="bg-white rounded-2xl overflow-y-auto shadow-md p-6 flex-[2]"
        >
          <h3 className="font-semibold text-gray-800 mb-6 text-lg">
            Generated Course Materials
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
            {materials.map((item, index) => (
              <div
                key={index}
                className="group relative border border-green-100 rounded-2xl p-5 bg-white shadow-sm hover:shadow-lg transition-all duration-300 hover:scale-[1.03] hover:border-green-400"
              >
              
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-green-400 to-green-500 rounded-t-2xl" />

                <h4 className="font-semibold text-gray-800 group-hover:text-green-600 transition-colors">
                  {item.title}
                </h4>
                <p className="text-sm text-gray-500 mt-1">{item.date}</p>
                <p className="text-xs text-gray-400 mt-1">
                  Generated by{" "}
                  <span className="text-green-500 font-medium">Gemini AI</span>
                </p>

                <div className="flex justify-between items-center mt-5">
                  <button className="flex items-center gap-1 border border-green-500 text-green-500 hover:bg-green-500 hover:text-white px-3 py-1.5 rounded-md text-sm transition-all duration-300 hover:shadow-md">
                    <PictureAsPdf fontSize="small" />
                    PDF
                  </button>
                  <button className="border border-green-500 text-green-500 hover:bg-green-500 hover:text-white px-3 py-1.5 rounded-md text-sm transition-all duration-300 hover:shadow-md">
                    View Q&amp;A
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Profile;
