name: React Frontend Build

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # replace with your Node version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          cd Frontend
          npm install

      # Step 4: Build the React app
      - name: Build React App
        run: |
          cd Frontend
          npm run build
